services:
  ollama:
    image: ollama/ollama
    runtime: nvidia
    environment:
      NVIDIA_VISIBLE_DEVICES: all
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: always
  anythingllm:
    image: mintplexlabs/anythingllm
    container_name: anythingllm
    ports:
      - "3001:3001"
    environment:
      # コンテナ環境変数として直接定義する（これが最優先で認識されます）
      - STORAGE_DIR=/app/server/storage
      - SERVER_PORT=3001
      - JWT_SECRET=your-random-secret-key-here
    volumes:
      - ./anythingllm:/app/server/storage
      - ./anythingllm/.env:/app/server/.env
    restart: unless-stopped
  searxng:
    image: searxng/searxng
    container_name: searxng
    ports:
      - "8080:8080"
    volumes:
      - "./searxng:/etc/searxng"
    environment:
      - BASE_URL=http://searxng:8080
      - SEARXNG_BASE_URL=http://searxng:8080
      - INSTANCE_NAME=SEARXNG
volumes:
  ollama:
  open-webui:
